// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LayoutGuest: typeof import('@/views/layouts/guest/layout-guest.vue')['default']
    Logo: typeof import('./../../views/components/logo.vue')['default']
  }
}
