name: Check & Fix Code Style

on:
  push:
    branches:
      - main
    paths:
      - "**.php"
      - "**.js"
      - "**.ts"
      - "**.vue"
      - "**.css"

jobs:
  php_style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.1.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix PHP styling

  frontend_style:
    runs-on: ubuntu-latest
    needs: php_style

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run prettier
        uses: borales/actions-yarn@v4
        with:
          cmd: format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix Frontend Styles
