name: Run Code Linters

on:
  push:
    branches:
      - main
    paths:
      - "**.php"
      - "**.js"
      - "**.ts"
      - "**.vue"

jobs:
  phpstan:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github

  eslint_type_check:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build-only

      - name: Check Typescript
        uses: borales/actions-yarn@v4
        with:
          cmd: type-check

      - name: Run ESLint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
